package com.example.demo.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TensuHenkouRirekiExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tensu_henkou_rireki
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tensu_henkou_rireki
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tensu_henkou_rireki
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tensu_henkou_rireki
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public TensuHenkouRirekiExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tensu_henkou_rireki
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tensu_henkou_rireki
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tensu_henkou_rireki
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tensu_henkou_rireki
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tensu_henkou_rireki
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tensu_henkou_rireki
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tensu_henkou_rireki
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tensu_henkou_rireki
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tensu_henkou_rireki
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tensu_henkou_rireki
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tensu_henkou_rireki
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRirekiIdIsNull() {
            addCriterion("rireki_id is null");
            return (Criteria) this;
        }

        public Criteria andRirekiIdIsNotNull() {
            addCriterion("rireki_id is not null");
            return (Criteria) this;
        }

        public Criteria andRirekiIdEqualTo(Integer value) {
            addCriterion("rireki_id =", value, "rirekiId");
            return (Criteria) this;
        }

        public Criteria andRirekiIdNotEqualTo(Integer value) {
            addCriterion("rireki_id <>", value, "rirekiId");
            return (Criteria) this;
        }

        public Criteria andRirekiIdGreaterThan(Integer value) {
            addCriterion("rireki_id >", value, "rirekiId");
            return (Criteria) this;
        }

        public Criteria andRirekiIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("rireki_id >=", value, "rirekiId");
            return (Criteria) this;
        }

        public Criteria andRirekiIdLessThan(Integer value) {
            addCriterion("rireki_id <", value, "rirekiId");
            return (Criteria) this;
        }

        public Criteria andRirekiIdLessThanOrEqualTo(Integer value) {
            addCriterion("rireki_id <=", value, "rirekiId");
            return (Criteria) this;
        }

        public Criteria andRirekiIdIn(List<Integer> values) {
            addCriterion("rireki_id in", values, "rirekiId");
            return (Criteria) this;
        }

        public Criteria andRirekiIdNotIn(List<Integer> values) {
            addCriterion("rireki_id not in", values, "rirekiId");
            return (Criteria) this;
        }

        public Criteria andRirekiIdBetween(Integer value1, Integer value2) {
            addCriterion("rireki_id between", value1, value2, "rirekiId");
            return (Criteria) this;
        }

        public Criteria andRirekiIdNotBetween(Integer value1, Integer value2) {
            addCriterion("rireki_id not between", value1, value2, "rirekiId");
            return (Criteria) this;
        }

        public Criteria andGakuseiIdIsNull() {
            addCriterion("gakusei_id is null");
            return (Criteria) this;
        }

        public Criteria andGakuseiIdIsNotNull() {
            addCriterion("gakusei_id is not null");
            return (Criteria) this;
        }

        public Criteria andGakuseiIdEqualTo(String value) {
            addCriterion("gakusei_id =", value, "gakuseiId");
            return (Criteria) this;
        }

        public Criteria andGakuseiIdNotEqualTo(String value) {
            addCriterion("gakusei_id <>", value, "gakuseiId");
            return (Criteria) this;
        }

        public Criteria andGakuseiIdGreaterThan(String value) {
            addCriterion("gakusei_id >", value, "gakuseiId");
            return (Criteria) this;
        }

        public Criteria andGakuseiIdGreaterThanOrEqualTo(String value) {
            addCriterion("gakusei_id >=", value, "gakuseiId");
            return (Criteria) this;
        }

        public Criteria andGakuseiIdLessThan(String value) {
            addCriterion("gakusei_id <", value, "gakuseiId");
            return (Criteria) this;
        }

        public Criteria andGakuseiIdLessThanOrEqualTo(String value) {
            addCriterion("gakusei_id <=", value, "gakuseiId");
            return (Criteria) this;
        }

        public Criteria andGakuseiIdLike(String value) {
            addCriterion("gakusei_id like", value, "gakuseiId");
            return (Criteria) this;
        }

        public Criteria andGakuseiIdNotLike(String value) {
            addCriterion("gakusei_id not like", value, "gakuseiId");
            return (Criteria) this;
        }

        public Criteria andGakuseiIdIn(List<String> values) {
            addCriterion("gakusei_id in", values, "gakuseiId");
            return (Criteria) this;
        }

        public Criteria andGakuseiIdNotIn(List<String> values) {
            addCriterion("gakusei_id not in", values, "gakuseiId");
            return (Criteria) this;
        }

        public Criteria andGakuseiIdBetween(String value1, String value2) {
            addCriterion("gakusei_id between", value1, value2, "gakuseiId");
            return (Criteria) this;
        }

        public Criteria andGakuseiIdNotBetween(String value1, String value2) {
            addCriterion("gakusei_id not between", value1, value2, "gakuseiId");
            return (Criteria) this;
        }

        public Criteria andKagenTensuIsNull() {
            addCriterion("kagen_tensu is null");
            return (Criteria) this;
        }

        public Criteria andKagenTensuIsNotNull() {
            addCriterion("kagen_tensu is not null");
            return (Criteria) this;
        }

        public Criteria andKagenTensuEqualTo(String value) {
            addCriterion("kagen_tensu =", value, "kagenTensu");
            return (Criteria) this;
        }

        public Criteria andKagenTensuNotEqualTo(String value) {
            addCriterion("kagen_tensu <>", value, "kagenTensu");
            return (Criteria) this;
        }

        public Criteria andKagenTensuGreaterThan(String value) {
            addCriterion("kagen_tensu >", value, "kagenTensu");
            return (Criteria) this;
        }

        public Criteria andKagenTensuGreaterThanOrEqualTo(String value) {
            addCriterion("kagen_tensu >=", value, "kagenTensu");
            return (Criteria) this;
        }

        public Criteria andKagenTensuLessThan(String value) {
            addCriterion("kagen_tensu <", value, "kagenTensu");
            return (Criteria) this;
        }

        public Criteria andKagenTensuLessThanOrEqualTo(String value) {
            addCriterion("kagen_tensu <=", value, "kagenTensu");
            return (Criteria) this;
        }

        public Criteria andKagenTensuLike(String value) {
            addCriterion("kagen_tensu like", value, "kagenTensu");
            return (Criteria) this;
        }

        public Criteria andKagenTensuNotLike(String value) {
            addCriterion("kagen_tensu not like", value, "kagenTensu");
            return (Criteria) this;
        }

        public Criteria andKagenTensuIn(List<String> values) {
            addCriterion("kagen_tensu in", values, "kagenTensu");
            return (Criteria) this;
        }

        public Criteria andKagenTensuNotIn(List<String> values) {
            addCriterion("kagen_tensu not in", values, "kagenTensu");
            return (Criteria) this;
        }

        public Criteria andKagenTensuBetween(String value1, String value2) {
            addCriterion("kagen_tensu between", value1, value2, "kagenTensu");
            return (Criteria) this;
        }

        public Criteria andKagenTensuNotBetween(String value1, String value2) {
            addCriterion("kagen_tensu not between", value1, value2, "kagenTensu");
            return (Criteria) this;
        }

        public Criteria andRiyuIdIsNull() {
            addCriterion("riyu_id is null");
            return (Criteria) this;
        }

        public Criteria andRiyuIdIsNotNull() {
            addCriterion("riyu_id is not null");
            return (Criteria) this;
        }

        public Criteria andRiyuIdEqualTo(Integer value) {
            addCriterion("riyu_id =", value, "riyuId");
            return (Criteria) this;
        }

        public Criteria andRiyuIdNotEqualTo(Integer value) {
            addCriterion("riyu_id <>", value, "riyuId");
            return (Criteria) this;
        }

        public Criteria andRiyuIdGreaterThan(Integer value) {
            addCriterion("riyu_id >", value, "riyuId");
            return (Criteria) this;
        }

        public Criteria andRiyuIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("riyu_id >=", value, "riyuId");
            return (Criteria) this;
        }

        public Criteria andRiyuIdLessThan(Integer value) {
            addCriterion("riyu_id <", value, "riyuId");
            return (Criteria) this;
        }

        public Criteria andRiyuIdLessThanOrEqualTo(Integer value) {
            addCriterion("riyu_id <=", value, "riyuId");
            return (Criteria) this;
        }

        public Criteria andRiyuIdIn(List<Integer> values) {
            addCriterion("riyu_id in", values, "riyuId");
            return (Criteria) this;
        }

        public Criteria andRiyuIdNotIn(List<Integer> values) {
            addCriterion("riyu_id not in", values, "riyuId");
            return (Criteria) this;
        }

        public Criteria andRiyuIdBetween(Integer value1, Integer value2) {
            addCriterion("riyu_id between", value1, value2, "riyuId");
            return (Criteria) this;
        }

        public Criteria andRiyuIdNotBetween(Integer value1, Integer value2) {
            addCriterion("riyu_id not between", value1, value2, "riyuId");
            return (Criteria) this;
        }

        public Criteria andHasseiBiIsNull() {
            addCriterion("hassei_bi is null");
            return (Criteria) this;
        }

        public Criteria andHasseiBiIsNotNull() {
            addCriterion("hassei_bi is not null");
            return (Criteria) this;
        }

        public Criteria andHasseiBiEqualTo(String value) {
            addCriterion("hassei_bi =", value, "hasseiBi");
            return (Criteria) this;
        }

        public Criteria andHasseiBiNotEqualTo(String value) {
            addCriterion("hassei_bi <>", value, "hasseiBi");
            return (Criteria) this;
        }

        public Criteria andHasseiBiGreaterThan(String value) {
            addCriterion("hassei_bi >", value, "hasseiBi");
            return (Criteria) this;
        }

        public Criteria andHasseiBiGreaterThanOrEqualTo(String value) {
            addCriterion("hassei_bi >=", value, "hasseiBi");
            return (Criteria) this;
        }

        public Criteria andHasseiBiLessThan(String value) {
            addCriterion("hassei_bi <", value, "hasseiBi");
            return (Criteria) this;
        }

        public Criteria andHasseiBiLessThanOrEqualTo(String value) {
            addCriterion("hassei_bi <=", value, "hasseiBi");
            return (Criteria) this;
        }

        public Criteria andHasseiBiLike(String value) {
            addCriterion("hassei_bi like", value, "hasseiBi");
            return (Criteria) this;
        }

        public Criteria andHasseiBiNotLike(String value) {
            addCriterion("hassei_bi not like", value, "hasseiBi");
            return (Criteria) this;
        }

        public Criteria andHasseiBiIn(List<String> values) {
            addCriterion("hassei_bi in", values, "hasseiBi");
            return (Criteria) this;
        }

        public Criteria andHasseiBiNotIn(List<String> values) {
            addCriterion("hassei_bi not in", values, "hasseiBi");
            return (Criteria) this;
        }

        public Criteria andHasseiBiBetween(String value1, String value2) {
            addCriterion("hassei_bi between", value1, value2, "hasseiBi");
            return (Criteria) this;
        }

        public Criteria andHasseiBiNotBetween(String value1, String value2) {
            addCriterion("hassei_bi not between", value1, value2, "hasseiBi");
            return (Criteria) this;
        }

        public Criteria andBikouIsNull() {
            addCriterion("bikou is null");
            return (Criteria) this;
        }

        public Criteria andBikouIsNotNull() {
            addCriterion("bikou is not null");
            return (Criteria) this;
        }

        public Criteria andBikouEqualTo(String value) {
            addCriterion("bikou =", value, "bikou");
            return (Criteria) this;
        }

        public Criteria andBikouNotEqualTo(String value) {
            addCriterion("bikou <>", value, "bikou");
            return (Criteria) this;
        }

        public Criteria andBikouGreaterThan(String value) {
            addCriterion("bikou >", value, "bikou");
            return (Criteria) this;
        }

        public Criteria andBikouGreaterThanOrEqualTo(String value) {
            addCriterion("bikou >=", value, "bikou");
            return (Criteria) this;
        }

        public Criteria andBikouLessThan(String value) {
            addCriterion("bikou <", value, "bikou");
            return (Criteria) this;
        }

        public Criteria andBikouLessThanOrEqualTo(String value) {
            addCriterion("bikou <=", value, "bikou");
            return (Criteria) this;
        }

        public Criteria andBikouLike(String value) {
            addCriterion("bikou like", value, "bikou");
            return (Criteria) this;
        }

        public Criteria andBikouNotLike(String value) {
            addCriterion("bikou not like", value, "bikou");
            return (Criteria) this;
        }

        public Criteria andBikouIn(List<String> values) {
            addCriterion("bikou in", values, "bikou");
            return (Criteria) this;
        }

        public Criteria andBikouNotIn(List<String> values) {
            addCriterion("bikou not in", values, "bikou");
            return (Criteria) this;
        }

        public Criteria andBikouBetween(String value1, String value2) {
            addCriterion("bikou between", value1, value2, "bikou");
            return (Criteria) this;
        }

        public Criteria andBikouNotBetween(String value1, String value2) {
            addCriterion("bikou not between", value1, value2, "bikou");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNull() {
            addCriterion("delete_flag is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNotNull() {
            addCriterion("delete_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagEqualTo(Integer value) {
            addCriterion("delete_flag =", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotEqualTo(Integer value) {
            addCriterion("delete_flag <>", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThan(Integer value) {
            addCriterion("delete_flag >", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("delete_flag >=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThan(Integer value) {
            addCriterion("delete_flag <", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThanOrEqualTo(Integer value) {
            addCriterion("delete_flag <=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIn(List<Integer> values) {
            addCriterion("delete_flag in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotIn(List<Integer> values) {
            addCriterion("delete_flag not in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagBetween(Integer value1, Integer value2) {
            addCriterion("delete_flag between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("delete_flag not between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andYobi1IsNull() {
            addCriterion("yobi_1 is null");
            return (Criteria) this;
        }

        public Criteria andYobi1IsNotNull() {
            addCriterion("yobi_1 is not null");
            return (Criteria) this;
        }

        public Criteria andYobi1EqualTo(String value) {
            addCriterion("yobi_1 =", value, "yobi1");
            return (Criteria) this;
        }

        public Criteria andYobi1NotEqualTo(String value) {
            addCriterion("yobi_1 <>", value, "yobi1");
            return (Criteria) this;
        }

        public Criteria andYobi1GreaterThan(String value) {
            addCriterion("yobi_1 >", value, "yobi1");
            return (Criteria) this;
        }

        public Criteria andYobi1GreaterThanOrEqualTo(String value) {
            addCriterion("yobi_1 >=", value, "yobi1");
            return (Criteria) this;
        }

        public Criteria andYobi1LessThan(String value) {
            addCriterion("yobi_1 <", value, "yobi1");
            return (Criteria) this;
        }

        public Criteria andYobi1LessThanOrEqualTo(String value) {
            addCriterion("yobi_1 <=", value, "yobi1");
            return (Criteria) this;
        }

        public Criteria andYobi1Like(String value) {
            addCriterion("yobi_1 like", value, "yobi1");
            return (Criteria) this;
        }

        public Criteria andYobi1NotLike(String value) {
            addCriterion("yobi_1 not like", value, "yobi1");
            return (Criteria) this;
        }

        public Criteria andYobi1In(List<String> values) {
            addCriterion("yobi_1 in", values, "yobi1");
            return (Criteria) this;
        }

        public Criteria andYobi1NotIn(List<String> values) {
            addCriterion("yobi_1 not in", values, "yobi1");
            return (Criteria) this;
        }

        public Criteria andYobi1Between(String value1, String value2) {
            addCriterion("yobi_1 between", value1, value2, "yobi1");
            return (Criteria) this;
        }

        public Criteria andYobi1NotBetween(String value1, String value2) {
            addCriterion("yobi_1 not between", value1, value2, "yobi1");
            return (Criteria) this;
        }

        public Criteria andYobi2IsNull() {
            addCriterion("yobi_2 is null");
            return (Criteria) this;
        }

        public Criteria andYobi2IsNotNull() {
            addCriterion("yobi_2 is not null");
            return (Criteria) this;
        }

        public Criteria andYobi2EqualTo(String value) {
            addCriterion("yobi_2 =", value, "yobi2");
            return (Criteria) this;
        }

        public Criteria andYobi2NotEqualTo(String value) {
            addCriterion("yobi_2 <>", value, "yobi2");
            return (Criteria) this;
        }

        public Criteria andYobi2GreaterThan(String value) {
            addCriterion("yobi_2 >", value, "yobi2");
            return (Criteria) this;
        }

        public Criteria andYobi2GreaterThanOrEqualTo(String value) {
            addCriterion("yobi_2 >=", value, "yobi2");
            return (Criteria) this;
        }

        public Criteria andYobi2LessThan(String value) {
            addCriterion("yobi_2 <", value, "yobi2");
            return (Criteria) this;
        }

        public Criteria andYobi2LessThanOrEqualTo(String value) {
            addCriterion("yobi_2 <=", value, "yobi2");
            return (Criteria) this;
        }

        public Criteria andYobi2Like(String value) {
            addCriterion("yobi_2 like", value, "yobi2");
            return (Criteria) this;
        }

        public Criteria andYobi2NotLike(String value) {
            addCriterion("yobi_2 not like", value, "yobi2");
            return (Criteria) this;
        }

        public Criteria andYobi2In(List<String> values) {
            addCriterion("yobi_2 in", values, "yobi2");
            return (Criteria) this;
        }

        public Criteria andYobi2NotIn(List<String> values) {
            addCriterion("yobi_2 not in", values, "yobi2");
            return (Criteria) this;
        }

        public Criteria andYobi2Between(String value1, String value2) {
            addCriterion("yobi_2 between", value1, value2, "yobi2");
            return (Criteria) this;
        }

        public Criteria andYobi2NotBetween(String value1, String value2) {
            addCriterion("yobi_2 not between", value1, value2, "yobi2");
            return (Criteria) this;
        }

        public Criteria andYobi3IsNull() {
            addCriterion("yobi_3 is null");
            return (Criteria) this;
        }

        public Criteria andYobi3IsNotNull() {
            addCriterion("yobi_3 is not null");
            return (Criteria) this;
        }

        public Criteria andYobi3EqualTo(String value) {
            addCriterion("yobi_3 =", value, "yobi3");
            return (Criteria) this;
        }

        public Criteria andYobi3NotEqualTo(String value) {
            addCriterion("yobi_3 <>", value, "yobi3");
            return (Criteria) this;
        }

        public Criteria andYobi3GreaterThan(String value) {
            addCriterion("yobi_3 >", value, "yobi3");
            return (Criteria) this;
        }

        public Criteria andYobi3GreaterThanOrEqualTo(String value) {
            addCriterion("yobi_3 >=", value, "yobi3");
            return (Criteria) this;
        }

        public Criteria andYobi3LessThan(String value) {
            addCriterion("yobi_3 <", value, "yobi3");
            return (Criteria) this;
        }

        public Criteria andYobi3LessThanOrEqualTo(String value) {
            addCriterion("yobi_3 <=", value, "yobi3");
            return (Criteria) this;
        }

        public Criteria andYobi3Like(String value) {
            addCriterion("yobi_3 like", value, "yobi3");
            return (Criteria) this;
        }

        public Criteria andYobi3NotLike(String value) {
            addCriterion("yobi_3 not like", value, "yobi3");
            return (Criteria) this;
        }

        public Criteria andYobi3In(List<String> values) {
            addCriterion("yobi_3 in", values, "yobi3");
            return (Criteria) this;
        }

        public Criteria andYobi3NotIn(List<String> values) {
            addCriterion("yobi_3 not in", values, "yobi3");
            return (Criteria) this;
        }

        public Criteria andYobi3Between(String value1, String value2) {
            addCriterion("yobi_3 between", value1, value2, "yobi3");
            return (Criteria) this;
        }

        public Criteria andYobi3NotBetween(String value1, String value2) {
            addCriterion("yobi_3 not between", value1, value2, "yobi3");
            return (Criteria) this;
        }

        public Criteria andTourokubiIsNull() {
            addCriterion("tourokubi is null");
            return (Criteria) this;
        }

        public Criteria andTourokubiIsNotNull() {
            addCriterion("tourokubi is not null");
            return (Criteria) this;
        }

        public Criteria andTourokubiEqualTo(Date value) {
            addCriterion("tourokubi =", value, "tourokubi");
            return (Criteria) this;
        }

        public Criteria andTourokubiNotEqualTo(Date value) {
            addCriterion("tourokubi <>", value, "tourokubi");
            return (Criteria) this;
        }

        public Criteria andTourokubiGreaterThan(Date value) {
            addCriterion("tourokubi >", value, "tourokubi");
            return (Criteria) this;
        }

        public Criteria andTourokubiGreaterThanOrEqualTo(Date value) {
            addCriterion("tourokubi >=", value, "tourokubi");
            return (Criteria) this;
        }

        public Criteria andTourokubiLessThan(Date value) {
            addCriterion("tourokubi <", value, "tourokubi");
            return (Criteria) this;
        }

        public Criteria andTourokubiLessThanOrEqualTo(Date value) {
            addCriterion("tourokubi <=", value, "tourokubi");
            return (Criteria) this;
        }

        public Criteria andTourokubiIn(List<Date> values) {
            addCriterion("tourokubi in", values, "tourokubi");
            return (Criteria) this;
        }

        public Criteria andTourokubiNotIn(List<Date> values) {
            addCriterion("tourokubi not in", values, "tourokubi");
            return (Criteria) this;
        }

        public Criteria andTourokubiBetween(Date value1, Date value2) {
            addCriterion("tourokubi between", value1, value2, "tourokubi");
            return (Criteria) this;
        }

        public Criteria andTourokubiNotBetween(Date value1, Date value2) {
            addCriterion("tourokubi not between", value1, value2, "tourokubi");
            return (Criteria) this;
        }

        public Criteria andTourokusyaIsNull() {
            addCriterion("tourokusya is null");
            return (Criteria) this;
        }

        public Criteria andTourokusyaIsNotNull() {
            addCriterion("tourokusya is not null");
            return (Criteria) this;
        }

        public Criteria andTourokusyaEqualTo(String value) {
            addCriterion("tourokusya =", value, "tourokusya");
            return (Criteria) this;
        }

        public Criteria andTourokusyaNotEqualTo(String value) {
            addCriterion("tourokusya <>", value, "tourokusya");
            return (Criteria) this;
        }

        public Criteria andTourokusyaGreaterThan(String value) {
            addCriterion("tourokusya >", value, "tourokusya");
            return (Criteria) this;
        }

        public Criteria andTourokusyaGreaterThanOrEqualTo(String value) {
            addCriterion("tourokusya >=", value, "tourokusya");
            return (Criteria) this;
        }

        public Criteria andTourokusyaLessThan(String value) {
            addCriterion("tourokusya <", value, "tourokusya");
            return (Criteria) this;
        }

        public Criteria andTourokusyaLessThanOrEqualTo(String value) {
            addCriterion("tourokusya <=", value, "tourokusya");
            return (Criteria) this;
        }

        public Criteria andTourokusyaLike(String value) {
            addCriterion("tourokusya like", value, "tourokusya");
            return (Criteria) this;
        }

        public Criteria andTourokusyaNotLike(String value) {
            addCriterion("tourokusya not like", value, "tourokusya");
            return (Criteria) this;
        }

        public Criteria andTourokusyaIn(List<String> values) {
            addCriterion("tourokusya in", values, "tourokusya");
            return (Criteria) this;
        }

        public Criteria andTourokusyaNotIn(List<String> values) {
            addCriterion("tourokusya not in", values, "tourokusya");
            return (Criteria) this;
        }

        public Criteria andTourokusyaBetween(String value1, String value2) {
            addCriterion("tourokusya between", value1, value2, "tourokusya");
            return (Criteria) this;
        }

        public Criteria andTourokusyaNotBetween(String value1, String value2) {
            addCriterion("tourokusya not between", value1, value2, "tourokusya");
            return (Criteria) this;
        }

        public Criteria andKousinbiIsNull() {
            addCriterion("kousinbi is null");
            return (Criteria) this;
        }

        public Criteria andKousinbiIsNotNull() {
            addCriterion("kousinbi is not null");
            return (Criteria) this;
        }

        public Criteria andKousinbiEqualTo(Date value) {
            addCriterion("kousinbi =", value, "kousinbi");
            return (Criteria) this;
        }

        public Criteria andKousinbiNotEqualTo(Date value) {
            addCriterion("kousinbi <>", value, "kousinbi");
            return (Criteria) this;
        }

        public Criteria andKousinbiGreaterThan(Date value) {
            addCriterion("kousinbi >", value, "kousinbi");
            return (Criteria) this;
        }

        public Criteria andKousinbiGreaterThanOrEqualTo(Date value) {
            addCriterion("kousinbi >=", value, "kousinbi");
            return (Criteria) this;
        }

        public Criteria andKousinbiLessThan(Date value) {
            addCriterion("kousinbi <", value, "kousinbi");
            return (Criteria) this;
        }

        public Criteria andKousinbiLessThanOrEqualTo(Date value) {
            addCriterion("kousinbi <=", value, "kousinbi");
            return (Criteria) this;
        }

        public Criteria andKousinbiIn(List<Date> values) {
            addCriterion("kousinbi in", values, "kousinbi");
            return (Criteria) this;
        }

        public Criteria andKousinbiNotIn(List<Date> values) {
            addCriterion("kousinbi not in", values, "kousinbi");
            return (Criteria) this;
        }

        public Criteria andKousinbiBetween(Date value1, Date value2) {
            addCriterion("kousinbi between", value1, value2, "kousinbi");
            return (Criteria) this;
        }

        public Criteria andKousinbiNotBetween(Date value1, Date value2) {
            addCriterion("kousinbi not between", value1, value2, "kousinbi");
            return (Criteria) this;
        }

        public Criteria andKousinsyaIsNull() {
            addCriterion("kousinsya is null");
            return (Criteria) this;
        }

        public Criteria andKousinsyaIsNotNull() {
            addCriterion("kousinsya is not null");
            return (Criteria) this;
        }

        public Criteria andKousinsyaEqualTo(String value) {
            addCriterion("kousinsya =", value, "kousinsya");
            return (Criteria) this;
        }

        public Criteria andKousinsyaNotEqualTo(String value) {
            addCriterion("kousinsya <>", value, "kousinsya");
            return (Criteria) this;
        }

        public Criteria andKousinsyaGreaterThan(String value) {
            addCriterion("kousinsya >", value, "kousinsya");
            return (Criteria) this;
        }

        public Criteria andKousinsyaGreaterThanOrEqualTo(String value) {
            addCriterion("kousinsya >=", value, "kousinsya");
            return (Criteria) this;
        }

        public Criteria andKousinsyaLessThan(String value) {
            addCriterion("kousinsya <", value, "kousinsya");
            return (Criteria) this;
        }

        public Criteria andKousinsyaLessThanOrEqualTo(String value) {
            addCriterion("kousinsya <=", value, "kousinsya");
            return (Criteria) this;
        }

        public Criteria andKousinsyaLike(String value) {
            addCriterion("kousinsya like", value, "kousinsya");
            return (Criteria) this;
        }

        public Criteria andKousinsyaNotLike(String value) {
            addCriterion("kousinsya not like", value, "kousinsya");
            return (Criteria) this;
        }

        public Criteria andKousinsyaIn(List<String> values) {
            addCriterion("kousinsya in", values, "kousinsya");
            return (Criteria) this;
        }

        public Criteria andKousinsyaNotIn(List<String> values) {
            addCriterion("kousinsya not in", values, "kousinsya");
            return (Criteria) this;
        }

        public Criteria andKousinsyaBetween(String value1, String value2) {
            addCriterion("kousinsya between", value1, value2, "kousinsya");
            return (Criteria) this;
        }

        public Criteria andKousinsyaNotBetween(String value1, String value2) {
            addCriterion("kousinsya not between", value1, value2, "kousinsya");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tensu_henkou_rireki
     *
     * @mbg.generated do_not_delete_during_merge Thu Oct 23 21:11:02 JST 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tensu_henkou_rireki
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}