package com.example.demo.entity;

import java.util.Date;

public class TensuHenkouRireki {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tensu_henkou_rireki.rireki_id
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    private Integer rirekiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tensu_henkou_rireki.gakusei_id
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    private Integer gakuseiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tensu_henkou_rireki.kagen_tensu
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    private String kagenTensu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tensu_henkou_rireki.riyu_id
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    private Integer riyuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tensu_henkou_rireki.hassei_bi
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    private String hasseiBi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tensu_henkou_rireki.bikou
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    private String bikou;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tensu_henkou_rireki.delete_flag
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    private Integer deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tensu_henkou_rireki.yobi_1
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    private String yobi1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tensu_henkou_rireki.yobi_2
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    private String yobi2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tensu_henkou_rireki.yobi_3
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    private String yobi3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tensu_henkou_rireki.tourokubi
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    private Date tourokubi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tensu_henkou_rireki.tourokusya
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    private String tourokusya;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tensu_henkou_rireki.kousinbi
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    private Date kousinbi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tensu_henkou_rireki.kousinsya
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    private String kousinsya;
    
    
    private String gutaiRiyu;

    public String getGutaiRiyu() {
		return gutaiRiyu;
	}

	public void setGutaiRiyu(String gutaiRiyu) {
		this.gutaiRiyu = gutaiRiyu;
	}
	
	private String namae;
	
	public String getNamae() {
		return namae;
	}

	public void setNamae(String namae) {
		this.namae = namae;
	}
	
	private Integer newGakuseiId;
	
	public Integer getNewGakuseiId() {
		return newGakuseiId;
	}

	public void setNewGakuseiId(Integer newGakuseiId) {
		this.newGakuseiId = newGakuseiId;
	}
	
	private Integer oldGakuseiId;
	
	public Integer getOldGakuseiId() {
		return oldGakuseiId;
	}

	public void setOldGakuseiId(Integer oldGakuseiId) {
		this.oldGakuseiId = oldGakuseiId;
	}
	
	private Integer kurasuId;
	
	public Integer getKurasuId() {
		return kurasuId;
	}

	public void setKurasuId(Integer kurasuId) {
		this.kurasuId = kurasuId;
	}

	private String kurasuNamae;
	
	public String getKurasuNamae() {
		return kurasuNamae;
	}

	public void setKurasuNamae(String kurasuNamae) {
		this.kurasuNamae = kurasuNamae;
	}
	
	private Integer tensu;
	
	public Integer getTensu() {
		return tensu;
	}
	public void setTensu(Integer tensu) {
		this.tensu = tensu;
	}
	

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tensu_henkou_rireki.rireki_id
     *
     * @return the value of tensu_henkou_rireki.rireki_id
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public Integer getRirekiId() {
        return rirekiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tensu_henkou_rireki.rireki_id
     *
     * @param rirekiId the value for tensu_henkou_rireki.rireki_id
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public void setRirekiId(Integer rirekiId) {
        this.rirekiId = rirekiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tensu_henkou_rireki.gakusei_id
     *
     * @return the value of tensu_henkou_rireki.gakusei_id
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public Integer getGakuseiId() {
        return gakuseiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tensu_henkou_rireki.gakusei_id
     *
     * @param gakuseiId the value for tensu_henkou_rireki.gakusei_id
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public void setGakuseiId(Integer gakuseiId) {
        this.gakuseiId = gakuseiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tensu_henkou_rireki.kagen_tensu
     *
     * @return the value of tensu_henkou_rireki.kagen_tensu
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public String getKagenTensu() {
        return kagenTensu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tensu_henkou_rireki.kagen_tensu
     *
     * @param kagenTensu the value for tensu_henkou_rireki.kagen_tensu
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public void setKagenTensu(String kagenTensu) {
        this.kagenTensu = kagenTensu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tensu_henkou_rireki.riyu_id
     *
     * @return the value of tensu_henkou_rireki.riyu_id
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public Integer getRiyuId() {
        return riyuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tensu_henkou_rireki.riyu_id
     *
     * @param riyuId the value for tensu_henkou_rireki.riyu_id
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public void setRiyuId(Integer riyuId) {
        this.riyuId = riyuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tensu_henkou_rireki.hassei_bi
     *
     * @return the value of tensu_henkou_rireki.hassei_bi
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public String getHasseiBi() {
        return hasseiBi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tensu_henkou_rireki.hassei_bi
     *
     * @param hasseiBi the value for tensu_henkou_rireki.hassei_bi
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public void setHasseiBi(String hasseiBi) {
        this.hasseiBi = hasseiBi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tensu_henkou_rireki.bikou
     *
     * @return the value of tensu_henkou_rireki.bikou
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public String getBikou() {
        return bikou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tensu_henkou_rireki.bikou
     *
     * @param bikou the value for tensu_henkou_rireki.bikou
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public void setBikou(String bikou) {
        this.bikou = bikou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tensu_henkou_rireki.delete_flag
     *
     * @return the value of tensu_henkou_rireki.delete_flag
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tensu_henkou_rireki.delete_flag
     *
     * @param deleteFlag the value for tensu_henkou_rireki.delete_flag
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tensu_henkou_rireki.yobi_1
     *
     * @return the value of tensu_henkou_rireki.yobi_1
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public String getYobi1() {
        return yobi1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tensu_henkou_rireki.yobi_1
     *
     * @param yobi1 the value for tensu_henkou_rireki.yobi_1
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public void setYobi1(String yobi1) {
        this.yobi1 = yobi1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tensu_henkou_rireki.yobi_2
     *
     * @return the value of tensu_henkou_rireki.yobi_2
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public String getYobi2() {
        return yobi2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tensu_henkou_rireki.yobi_2
     *
     * @param yobi2 the value for tensu_henkou_rireki.yobi_2
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public void setYobi2(String yobi2) {
        this.yobi2 = yobi2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tensu_henkou_rireki.yobi_3
     *
     * @return the value of tensu_henkou_rireki.yobi_3
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public String getYobi3() {
        return yobi3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tensu_henkou_rireki.yobi_3
     *
     * @param yobi3 the value for tensu_henkou_rireki.yobi_3
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public void setYobi3(String yobi3) {
        this.yobi3 = yobi3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tensu_henkou_rireki.tourokubi
     *
     * @return the value of tensu_henkou_rireki.tourokubi
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public Date getTourokubi() {
        return tourokubi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tensu_henkou_rireki.tourokubi
     *
     * @param tourokubi the value for tensu_henkou_rireki.tourokubi
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public void setTourokubi(Date tourokubi) {
        this.tourokubi = tourokubi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tensu_henkou_rireki.tourokusya
     *
     * @return the value of tensu_henkou_rireki.tourokusya
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public String getTourokusya() {
        return tourokusya;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tensu_henkou_rireki.tourokusya
     *
     * @param tourokusya the value for tensu_henkou_rireki.tourokusya
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public void setTourokusya(String tourokusya) {
        this.tourokusya = tourokusya;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tensu_henkou_rireki.kousinbi
     *
     * @return the value of tensu_henkou_rireki.kousinbi
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public Date getKousinbi() {
        return kousinbi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tensu_henkou_rireki.kousinbi
     *
     * @param kousinbi the value for tensu_henkou_rireki.kousinbi
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public void setKousinbi(Date kousinbi) {
        this.kousinbi = kousinbi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tensu_henkou_rireki.kousinsya
     *
     * @return the value of tensu_henkou_rireki.kousinsya
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public String getKousinsya() {
        return kousinsya;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tensu_henkou_rireki.kousinsya
     *
     * @param kousinsya the value for tensu_henkou_rireki.kousinsya
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    public void setKousinsya(String kousinsya) {
        this.kousinsya = kousinsya;
    }
}