package com.example.demo.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.demo.entity.TensuHenkouRireki;
import com.example.demo.entity.TensuHenkouRirekiExample;

@Mapper

public interface TensuHenkouRirekiMapper {
	 
	 /* 一覧検索 */
	 List<TensuHenkouRireki> findAll();
	  
	 List<TensuHenkouRireki> findByGakuseiId(Integer gakuseiId);
	 
	 /* あいまい検索 */
	 List<TensuHenkouRireki> findByNamaeContaining(String namae);
	 
	 TensuHenkouRireki findByRirekiId(Integer rirekiId);
	 
	 void updateTensu(TensuHenkouRireki rireki);
	 
	 void updateDeleteFlag(TensuHenkouRireki rireki);
	 
	 void insertTensuRecord(TensuHenkouRireki tensuHenkouRireki);
	 
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tensu_henkou_rireki
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    long countByExample(TensuHenkouRirekiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tensu_henkou_rireki
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    int deleteByExample(TensuHenkouRirekiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tensu_henkou_rireki
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    int deleteByPrimaryKey(Integer rirekiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tensu_henkou_rireki
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    int insert(TensuHenkouRireki row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tensu_henkou_rireki
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    int insertSelective(TensuHenkouRireki row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tensu_henkou_rireki
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    List<TensuHenkouRireki> selectByExample(TensuHenkouRirekiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tensu_henkou_rireki
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    TensuHenkouRireki selectByPrimaryKey(Integer rirekiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tensu_henkou_rireki
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    int updateByExampleSelective(@Param("row") TensuHenkouRireki row, @Param("example") TensuHenkouRirekiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tensu_henkou_rireki
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    int updateByExample(@Param("row") TensuHenkouRireki row, @Param("example") TensuHenkouRirekiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tensu_henkou_rireki
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    int updateByPrimaryKeySelective(TensuHenkouRireki row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tensu_henkou_rireki
     *
     * @mbg.generated Thu Oct 23 21:11:02 JST 2025
     */
    int updateByPrimaryKey(TensuHenkouRireki row);
}